-d E:\FPGA_work\Gowin\TangNano_20k\bittest_lcd800\impl\gwsynthesis\lcd_test.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst E:\FPGA_work\Gowin\TangNano_20k\bittest_lcd800\src\lcd.cst
-cfg E:\FPGA_work\Gowin\TangNano_20k\bittest_lcd800\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
