-d E:\FPGA_work\Gowin\GW020A\uart_loop\impl\gwsynthesis\uart_Hello.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst E:\FPGA_work\Gowin\GW020A\uart_loop\src\top.cst
-cfg E:\FPGA_work\Gowin\GW020A\uart_loop\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
