-d E:\FPGA_work\Gowin\GW020AB\all_test\impl\gwsynthesis\top.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst E:\FPGA_work\Gowin\GW020AB\all_test\src\top.cst
-cfg E:\FPGA_work\Gowin\GW020AB\all_test\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
