-d D:\Users\HUIP\Desktop\PMOD_LED_PWM\impl\gwsynthesis\PMOD_LED.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst D:\Users\HUIP\Desktop\PMOD_LED_PWM\src\top.cst
-cfg D:\Users\HUIP\Desktop\PMOD_LED_PWM\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
