-d E:\FPGA_work\Gowin\TangNano_1k\colorflow_lcd480\impl\gwsynthesis\lcd_test.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst E:\FPGA_work\Gowin\TangNano_1k\colorflow_lcd480\src\lcd.cst
-cfg E:\FPGA_work\Gowin\TangNano_1k\colorflow_lcd480\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
