-d E:\FPGA_work\Gowin\TangNano_9k\bittest_hdmi720P\impl\gwsynthesis\lcd_test.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst E:\FPGA_work\Gowin\TangNano_9k\bittest_hdmi720P\src\lcd.cst
-cfg E:\FPGA_work\Gowin\TangNano_9k\bittest_hdmi720P\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
