-d D:\Users\HUIP\Desktop\VGA_GuessHand\impl\gwsynthesis\VGA_GuessHand.vg
-p GW1N-9C-LQFP144-6
-pn GW1N-LV9LQ144C6/I5
-cst D:\Users\HUIP\Desktop\VGA_GuessHand\src\top.cst
-cfg D:\Users\HUIP\Desktop\VGA_GuessHand\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
