-d D:\Users\HUIP\Desktop\IIC_OLED_4\impl\gwsynthesis\IIC_OLED_4.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst D:\Users\HUIP\Desktop\IIC_OLED_4\src\top.cst
-cfg D:\Users\HUIP\Desktop\IIC_OLED_4\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
