-d D:\Users\HUIP\Desktop\udp_gmii_send\impl\gwsynthesis\top.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst D:\Users\HUIP\Desktop\udp_gmii_send\src\top.cst
-cfg D:\Users\HUIP\Desktop\udp_gmii_send\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
